"""initial schema

Revision ID: d0d7b6bf2d9a
Revises: 
Create Date: 2026-09-10 03:28:23.269274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0d7b6bf2d9a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bidders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('pan', sa.String(), nullable=True),
    sa.Column('gstin', sa.String(), nullable=True),
    sa.Column('cin', sa.String(), nullable=True),
    sa.Column('udyam', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('PROCUREMENT_OFFICER', 'PROCUREMENT_ADMIN', 'COMPLIANCE_REVIEWER', 'DEPARTMENT_ADMIN', 'AUDIT_OFFICER', 'SENIOR_APPROVING_AUTHORITY', name='role'), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor_user_id', sa.String(), nullable=True),
    sa.Column('actor_name', sa.String(), nullable=False),
    sa.Column('actor_role', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('tender_id', sa.String(), nullable=True),
    sa.Column('bidder_id', sa.String(), nullable=True),
    sa.Column('requirement_key', sa.String(), nullable=True),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('evidence_ref', sa.String(), nullable=True),
    sa.Column('override', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_tender_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'UNDER_EVALUATION', 'CLOSED', 'AWARDED', name='tenderstatus'), nullable=True),
    sa.Column('rule_version', sa.String(), nullable=True),
    sa.Column('assigned_officer_id', sa.String(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('bidder_submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tender_id', sa.String(), nullable=False),
    sa.Column('bidder_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_VERIFICATION', 'UNDER_REVIEW', 'LIKELY_COMPLIANT', 'REQUIRES_REVIEW', 'POTENTIALLY_NON_COMPLIANT', 'NOT_QUALIFIED', 'QUALIFIED', name='submissionstatus'), nullable=True),
    sa.Column('compliance_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=True),
    sa.Column('ai_recommendation', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bidder_id'], ['bidders.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_requirements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tender_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('STATUTORY', 'FINANCIAL', 'TECHNICAL', 'ELIGIBILITY', 'CERTIFICATION', 'EXPERIENCE', 'LOCAL_CONTENT', 'OEM', name='requirementcategory'), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=True),
    sa.Column('expected_value', sa.String(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('doc_type', sa.Enum('GST_CERTIFICATE', 'UDYAM_CERTIFICATE', 'PAN_CARD', 'INCORPORATION_CERTIFICATE', 'STARTUP_INDIA_CERTIFICATE', 'OEM_AUTHORIZATION', 'LOCAL_CONTENT_DECLARATION', 'EPFO_ESIC_DOCUMENT', 'NSIC_CERTIFICATE', 'TENDER_DECLARATION', 'AFFIDAVIT', name='documenttype'), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'VERIFIED', 'SUSPICIOUS', 'REJECTED', 'UNDER_REVIEW', name='documentstatus'), nullable=True),
    sa.Column('extracted_fields_json', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['bidder_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('requirement_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PASS', 'MISMATCH', 'MISSING', 'EXPIRING', 'REVIEW', 'FAIL', 'CLEAR', name='compliancestatus'), nullable=True),
    sa.Column('evidence_document_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('document_value', sa.String(), nullable=True),
    sa.Column('portal_value', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('reasons_json', sa.Text(), nullable=True),
    sa.Column('rule_version', sa.String(), nullable=True),
    sa.Column('rule_fired', sa.String(), nullable=True),
    sa.Column('human_action', sa.String(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('reviewer_comment', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['tender_requirements.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['bidder_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compliance_results')
    op.drop_table('documents')
    op.drop_table('tender_requirements')
    op.drop_table('bidder_submissions')
    op.drop_table('tenders')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('bidders')
    # ### end Alembic commands ###
